spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: REDIS # session存储类型[redis]
  jackson:
    serialization:
      write-dates-as-timestamps: true
  redis:
    host: 192.168.0.13
    port: 6379

server:
  servlet:
    session:
      timeout: 600 # session过期时间，最低时间一分钟
  port: 80

magic:
  security:
    browser:
      #      loginPage: /demo-signIn.html
      signUpUrl: /demo-signUp.html
      loginType: JSON
      logoutUrl: /imooc-logout.html # 配置自己的退出页面
    code:
      image:
        length: 4
        width: 100
        #url: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /qqLogin

logging:
  level:
    com.magic.security: debug

## 服务器分配的client-id和client-secret [服务测试]
security:
  oauth2:
    client:
      clientId: magic
      clientSecret: magic123





