spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  jackson:
    serialization:
      write-dates-as-timestamps: true

server:
  servlet:
    session:
      timeout: 600

magic:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginType: JSON
    code:
      image:
        length: 4
        width: 100
        #url: /user,/user/*
    social:
      qq:
        app-id: 217911
        app-secret: b68b1fe2abdf241466a0eae7731ab45
logging:
  level:
    com.magic.security: debug



