spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 100
    min-idle: 10
    min-evictable-idle-time-millis: 1800000
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
  session:
    store-type: redis # session存储类型[redis]
  jackson:
    serialization:
      write-dates-as-timestamps: true
  redis:
    host: 192.168.0.13
    port: 6379

## JPA
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        implicit-strategy: com.magic.security.rbac.repository.support.ImoocImplicitNamingStrategy

server:
  servlet:
    session:
      timeout: 600 # session过期时间，最低时间一分钟
  port: 80

magic:
  security:
    browser:
      #      loginPage: /demo-signIn.html
      signUpUrl: /demo-signUp.html
      loginType: REDIRECT
      logoutUrl: /imooc-logout.html # 配置自己的退出页面
      singInSuccessUrl: /manage.html

    code:
      image:
        length: 4
        width: 100
        #url: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /qqLogin
    oauth2:
      tokenStore: jwt
      ### 服务器分配的client-id和client-secret [服务测试]
      clients[0]:
        clientId: magic
        clientSecret: magic123
        accessTokenValidateSeconds: 7200
      client[1]:
        clientId: test
        clientSecret: test123

logging:
  level:
    org.springframework: info









